export const radicalNames = {
  "一": "one",
  "｜": "line, stick",
  "丶": "dot",
  "ノ": "bend, katakana no",
  "乙": "second, latter",
  "亅": "hook, hooked stick",
  "二": "two",
  "亠": "pot lid",
  "人": "human",
  "儿": "legs, human underneath",
  "入": "enter",
  "ハ": "eight, eight-head",
  "冂": "inverted box, window frame",
  "冖": "cover, wa crown",
  "冫": "ice, 2-stroke water",
  "几": "desk",
  "凵": "container, inbox",
  "刀": "sword",
  "力": "power, force",
  "勹": "embrace, wrap frame",
  "匕": "spoon hi",
  "匚": "box frame",
  "亡": "dead, hiding frame",
  "十": "ten, complete",
  "卜": "divination to",
  "卩": "seal",
  "厂": "cliff",
  "厶": "private",
  "又": "again, right hand",
  "口": "mouth, opening",
  "囗": "enclosure",
  "土": "earth",
  "士": "scholar, bachelor",
  "夂": "winter",
  "夕": "evening, sunset",
  "大": "big, very",
  "女": "woman, female",
  "子": "child, seed",
  "宀": "roof",
  "寸": "sun (unit of measurement)",
  "小": "small, insignificant",
  "尢": "lame",
  "尸": "corpse",
  "屮": "sprout",
  "山": "mountain",
  "巛": "river",
  "工": "work",
  "已": "oneself",
  "巾": "cloth, turban, scarf",
  "干": "dry",
  "幺": "short thread",
  "广": "dotted cliff",
  "廴": "long stride",
  "廾": "two hands, twenty",
  "弋": "ceremony, shoot, arrow",
  "弓": "bow",
  "彑": "pig's head",
  "彡": "hair, bristle, stubble, beard",
  "彳": "step",
  "心": "heart",
  "戈": "spear, halberd",
  "戸": "door, house",
  "手": "hand",
  "支": "branch",
  "攵": "strike, whip",
  "文": "script, literature",
  "斗": "dipper, measuring scoop",
  "斤": "axe",
  "方": "way, square, raft",
  "无": "have not",
  "日": "sun, day",
  "曰": "say",
  "月": "moon, month; body, flesh",
  "木": "tree",
  "欠": "yawn, lack",
  "止": "stop",
  "歹": "death, decay",
  "殳": "weapon, lance",
  "毋": "do not; mother",
  "比": "compare, compete",
  "毛": "fur, hair",
  "氏": "clan",
  "气": "steam, breath",
  "水": "water",
  "火": "fire",
  "爪": "claw, nail, talon",
  "父": "father",
  "爻": "mix, twine, cross",
  "爿": "split wood",
  "片": "(a) slice",
  "牙": "fang",
  "牛": "cow",
  "犬": "dog",
  "玄": "dark, profound",
  "王": "king; ball, jade",
  "瓜": "melon",
  "瓦": "tile",
  "甘": "sweet",
  "生": "life",
  "用": "use; (throw)",
  "田": "field",
  "疋": "bolt of cloth",
  "疒": "sickness",
  "癶": "footsteps",
  "白": "white",
  "皮": "skin",
  "皿": "dish",
  "目": "eye",
  "矛": "spear, pike",
  "矢": "arrow",
  "石": "stone",
  "示": "altar, display",
  "禸": "track",
  "禾": "two-branch tree",
  "穴": "cave",
  "立": "stand, erect",
  "竹": "bamboo",
  "米": "rice",
  "糸": "thread, string",
  "缶": "can, earthenware jar",
  "罒": "net",
  "羊": "sheep",
  "羽": "feather, wing",
  "⺹": "old",
  "而": "rake, beard",
  "耒": "plow",
  "耳": "ear",
  "聿": "brush",
  "肉": "meat",
  "臣": "minister, official",
  "自": "oneself",
  "至": "arrive",
  "臼": "mortar",
  "舌": "tongue",
  "舛": "opposite",
  "舟": "boat",
  "艮": "stopping",
  "色": "colour, prettiness",
  "⺾": "grass, vegetation",
  "虍": "tiger stripes",
  "虫": "insect",
  "血": "blood",
  "行": "go, do",
  "衣": "clothes",
  "西": "west",
  "見": "see",
  "角": "horn",
  "言": "speech",
  "谷": "valley",
  "豆": "bean",
  "豕": "pig",
  "豸": "cat, badger",
  "貝": "shell",
  "赤": "red, bare",
  "走": "run",
  "足": "foot",
  "身": "body",
  "車": "cart, car",
  "辛": "spicy, bitter",
  "辰": "morning",
  "辶": "walk",
  "⻏": "town (阝 right)",
  "邑": "village",
  "酉": "sake (rice-based alcoholic beverage)",
  "釆": "divide, distinguish, choose",
  "里": "village, mile",
  "金": "metal, gold",
  "長": "long, grow; leader",
  "門": "gate",
  "⻖": "mound, dam (阝 left)",
  "隶": "slave, capture",
  "隹": "old bird",
  "雨": "rain",
  "青": "green, blue",
  "非": "wrong",
  "面": "face",
  "革": "leather, rawhide",
  "韋": "tanned leather",
  "韭": "leek",
  "音": "sound",
  "頁": "big shell",
  "風": "wind",
  "飛": "fly",
  "食": "eat, food",
  "首": "neck, head",
  "香": "fragrant",
  "馬": "horse",
  "骨": "bone",
  "高": "tall, high",
  "髟": "hair",
  "鬥": "fight",
  "鬯": "herbs, sacrificial wine",
  "鬲": "tripod, cauldron",
  "鬼": "ghost, demon",
  "魚": "fish",
  "鳥": "bird",
  "鹵": "salt",
  "鹿": "deer",
  "麦": "wheat",
  "麻": "hemp, flax",
  "黄": "yellow",
  "黍": "millet",
  "黒": "black",
  "黹": "embroidery, needlework",
  "黽": "frog, amphibian",
  "鼎": "sacrificial tripod",
  "鼓": "drum",
  "鼠": "rat, mouse",
  "鼻": "nose",
  "齊": "even, uniformly",
  "歯": "tooth, molar",
  "竜": "dragon",
  "亀": "turtle, tortoise",
  "龠": "flute",
  "⺅": "Variant of 人 (human)",
  "𠆢": "Variant of 人 (human)",
  "マ": "Katakana ma",
  "九": "nine",
  "ユ": "Katakana yu",
  "乃": "from, whereupon",
  "刂": "Variant of 刀 (sword)",
  "⺌": "Variant of 小 (small, insignificant)",
  "川": "Variant of 巛 (river)",
  "也": "to be",
  "及": "reach out, exert, exercise, cause",
  "久": "long time, old story",
  "忄": "Variant of 心 (heart)",
  "扌": "Variant of 手 (hand)",
  "氵": "Variant of 水 (water)",
  "犭": "Variant of 犬 (dog)",
  "灬": "Variant of 火 (fire)",
  "元": "From 儿 (legs, human underneath)",
  "井": "(a) well",
  "勿": "not",
  "尤": "reasonable, plausible",
  "五": "five",
  "屯": "barracks, camp",
  "巴": "From 已 (oneself)",
  "礻": "cult, showing",
  "衤": "clothes, clothing",
  "世": "generation",
  "巨": "gigantic",
  "冊": "tome",
  "母": "Variant of 毋 (do not; mother)",
  "奄": "cover, obstruct",
  "岡": "mount, hill, knoll",
  "免": "excuse, dismissal",
  "斉": "alike, equal",
  "品": "goods, article",
  "無": "nothingness",
  "ヨ": "katakana yo",
  "并": "put together",
  "滴": "drip, drop"
};

export const partsOfSpeech = {
  "adj-f": "noun or verb acting prenominally",
  "adj-i": "adjective (keiyoushi)",
  "adj-ix": "adjective (keiyoushi) - yoi/ii class",
  "adj-ku": "'ku' adjective (archaic)",
  "adj-na": "adjectival nouns or quasi-adjectives (keiyodoshi)",
  "adj-nari": "archaic/formal form of na-adjective",
  "adj-no": "nouns which may take the genitive case particle 'no'",
  "adj-pn": "pre-noun adjectival (rentaishi)",
  "adj-shiku": "'shiku' adjective (archaic)",
  "adj-t": "'taru' adjective",
  "adv": "adverb (fukushi)",
  "adv-to": "adverb taking the 'to' particle",
  "arch": "archaism",
  "aux": "auxiliary",
  "aux-adj": "auxiliary adjective",
  "aux-v": "auxiliary verb",
  "conj": "conjunction",
  "ctr": "counter",
  "exp": "expressions (phrases, clauses, etc.)",
  "gai": "common loanword",
  "id": "idiomatic expression",
  "ik": "word containing irregular kana usage",
  "int": "interjection (kandoushi)",
  "n": "noun (common) (futsuumeishi)",
  "n-adv": "adverbial noun (fukushitekimeishi)",
  "n-pr": "proper noun",
  "n-pref": "noun, used as a prefix",
  "n-suf": "noun, used as a suffix",
  "n-t": "noun (temporal) (jisoumeishi)",
  "num": "numeric",
  "ok": "out-dated or obsolete kana usage",
  "pn": "pronoun",
  "pref": "prefix",
  "prt": "particle",
  "spec": "common words not included in frequency lists",
  "suf": "suffix",
  "uk": "word usually written using kana alone",
  "unc": "unclassified",
  "v1": "Ichidan verb",
  "v1-s": "Ichidan verb - kureru special class",
  "v2a-s": "Nidan verb with 'u' ending (archaic)",
  "v2b-k": "Nidan verb (upper class) with 'bu' ending (archaic)",
  "v2d-s": "Nidan verb (lower class) with 'dzu' ending (archaic)",
  "v2g-k": "Nidan verb (upper class) with 'gu' ending (archaic)",
  "v2g-s": "Nidan verb (lower class) with 'gu' ending (archaic)",
  "v2h-k": "Nidan verb (upper class) with 'hu/fu' ending (archaic)",
  "v2h-s": "Nidan verb (lower class) with 'hu/fu' ending (archaic)",
  "v2k-k": "Nidan verb (upper class) with 'ku' ending (archaic)",
  "v2k-s": "Nidan verb (lower class) with 'ku' ending (archaic)",
  "v2m-s": "Nidan verb (lower class) with 'mu' ending (archaic)",
  "v2n-s": "Nidan verb (lower class) with 'nu' ending (archaic)",
  "v2r-k": "Nidan verb (upper class) with 'ru' ending (archaic)",
  "v2r-s": "Nidan verb (lower class) with 'ru' ending (archaic)",
  "v2s-s": "Nidan verb (lower class) with 'su' ending (archaic)",
  "v2t-k": "Nidan verb (upper class) with 'tsu' ending (archaic)",
  "v2t-s": "Nidan verb (lower class) with 'tsu' ending (archaic)",
  "v2w-s": "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)",
  "v2y-k": "Nidan verb (upper class) with 'yu' ending (archaic)",
  "v2y-s": "Nidan verb (lower class) with 'yu' ending (archaic)",
  "v2z-s": "Nidan verb (lower class) with 'zu' ending (archaic)",
  "v4b": "Yodan verb with 'bu' ending (archaic)",
  "v4h": "Yodan verb with 'hu/fu' ending (archaic)",
  "v4k": "Yodan verb with 'ku' ending (archaic)",
  "v4m": "Yodan verb with 'mu' ending (archaic)",
  "v4r": "Yodan verb with 'ru' ending (archaic)",
  "v4s": "Yodan verb with 'su' ending (archaic)",
  "v4t": "Yodan verb with 'tsu' ending (archaic)",
  "v5aru": "Godan verb - -aru special class",
  "v5b": "Godan verb with 'bu' ending",
  "v5g": "Godan verb with 'gu' ending",
  "v5k": "Godan verb with 'ku' ending",
  "v5k-s": "Godan verb - Iku/Yuku special class",
  "v5m": "Godan verb with 'mu' ending",
  "v5n": "Godan verb with 'nu' ending",
  "v5r": "Godan verb with 'ru' ending",
  "v5r-i": "Godan verb with 'ru' ending (irregular verb)",
  "v5s": "Godan verb with 'su' ending",
  "v5t": "Godan verb with 'tsu' ending",
  "v5u": "Godan verb with 'u' ending",
  "v5u-s": "Godan verb with 'u' ending (special class)",
  "vi": "intransitive verb",
  "vk": "Kuru verb - special class",
  "vn": "irregular nu verb",
  "vr": "irregular ru verb, plain form ends with -ri",
  "vs": "noun or participle which takes the aux. verb suru",
  "vs-c": "su verb - precursor to the modern suru",
  "vs-i": "suru verb - included",
  "vs-s": "suru verb - special class",
  "vt": "transitive verb",
  "vz": "Ichidan verb - zuru verb (alternative form of -jiru verbs)"
};
